from app.models import Album

albums = [
    Album(
        title="Abbey Road",
        artist_id=2,
        track_data={
            1: "Come Together",
            2: "Something",
            3: "Maxwell's Silver Hammer",
            4: "Oh! Darling",
            5: "Octopus's Garden",
            6: "I Want You (She's So Heavy)",
            7: "Here Comes The Sun",
            8: "Because",
            9: "You Never Give Me Your Money",
            10: "Sun King",
            11: "Mean Mr. Mustard",
            12: "Polythene Pam",
            13: "She Came In Through The Bathroom Window",
            14: "Golden Slumbers",
            15: "Carry That Weight",
            16: "The End",
            17: "Her Majesty",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//f304ba0296794c6fc9d0e1cccd194ed0.jpg",
    ),
    Album(
        title="The Dark Side of the Moon",
        artist_id=3,
        track_data={
            1: "Speak to Me",
            2: "Breathe",
            3: "On the Run",
            4: "Time",
            5: "The Great Gig in the Sky",
            6: "Money",
            7: "Us and Them",
            8: "Any Colour You Like",
            9: "Brain Damage",
            10: "Eclipse",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//d4bdd038cacbec705e269edb0fd38419.png",
    ),
    Album(
        title="Led Zeppelin IV",
        artist_id=4,
        track_data={
            1: "Black Dog",
            2: "Rock and Roll",
            3: "The Battle of Evermore",
            4: "Stairway to Heaven",
            5: "Misty Mountain Hop",
            6: "Four Sticks",
            7: "Going to California",
            8: "When the Levee Breaks",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//1e6f99756d0342f891d3233ac1283d21.png",
    ),
    Album(
        title="A Night at the Opera",
        artist_id=5,
        track_data={
            1: "Death on Two Legs",
            2: "Lazing on a Sunday Afternoon",
            3: "You're My Best Friend",
            4: "I'm in Love with My Car",
            5: "'39",
            6: "Sweet Lady",
            7: "Seaside Rendezvous",
            8: "The Prophet's Song",
            9: "Love of My Life",
            10: "Good Company",
            11: "Bohemian Rhapsody",
            12: "God Save the Queen",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//d36a1f8075da4df6bb835b2f7eac1547.png",
    ),
    Album(
        title="Sticky Fingers",
        artist_id=1,
        track_data={
            1: "Brown Sugar",
            2: "Sway",
            3: "Wild Horses",
            4: "Can't You Hear Me Knocking",
            5: "You Gotta Move",
            6: "Bitch",
            7: "I Got the Blues",
            8: "Sister Morphine",
            9: "Dead Flowers",
            10: "Moonlight Mile",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//5ffc0e1908e44522c50a6e56300ec7ef.png",
    ),
    Album(
        title="Thriller",
        artist_id=8,
        track_data={
            1: "Wanna Be Startin' Somethin'",
            2: "Baby Be Mine",
            3: "The Girl Is Mine",
            4: "Thriller",
            5: "Beat It",
            6: "Billie Jean",
            7: "Human Nature",
            8: "P.Y.T. (Pretty Young Thing)",
            9: "The Lady in My Life",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//16916e04f2ff8c50bd47951cb9b5218c.jpg",
    ),
    Album(
        title="Like a Virgin",
        artist_id=9,
        track_data={
            1: "Material Girl",
            2: "Angel",
            3: "Like a Virgin",
            4: "Over and Over",
            5: "Love Don't Live Here Anymore",
            6: "Dress You Up",
            7: "Shoo-Bee-Doo",
            8: "Pretender",
            9: "Stay",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//a4ddbfef557fd92f733c307855b6fd80.png",
    ),
    Album(
        title="Rumours",
        artist_id=11,
        track_data={
            1: "Second Hand News",
            2: "Dreams",
            3: "Never Going Back Again",
            4: "Don't Stop",
            5: "Go Your Own Way",
            6: "Songbird",
            7: "The Chain",
            8: "You Make Loving Fun",
            9: "I Don't Want to Know",
            10: "Oh Daddy",
            11: "Gold Dust Woman",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//0b4716b42466ffa893ad3e3ab824318b.png",
    ),
    Album(
        title="Nevermind",
        artist_id=12,
        track_data={
            1: "Smells Like Teen Spirit",
            2: "In Bloom",
            3: "Come As You Are",
            4: "Breed",
            5: "Lithium",
            6: "Polly",
            7: "Territorial Pissings",
            8: "Drain You",
            9: "Lounge Act",
            10: "Stay Away",
            11: "On a Plain",
            12: "Something in the Way",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//49cc807f69d59746b6b04be3434e6637.png",
    ),
    Album(
        title="The Joshua Tree",
        artist_id=13,
        track_data={
            1: "Where the Streets Have No Name",
            2: "I Still Haven't Found What I'm Looking For",
            3: "With or Without You",
            4: "Bullet the Blue Sky",
            5: "Running to Stand Still",
            6: "Red Hill Mining Town",
            7: "In God's Country",
            8: "Trip Through Your Wires",
            9: "One Tree Hill",
            10: "Exit",
            11: "Mothers of the Disappeared",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//b746f016aef9f8a8274c3f377e0d6316.png",
    ),
    Album(
        title="Purple Rain",
        artist_id=14,
        track_data={
            1: "Let's Go Crazy",
            2: "Take Me With U",
            3: "The Beautiful Ones",
            4: "Computer Blue",
            5: "Darling Nikki",
            6: "When Doves Cry",
            7: "I Would Die 4 U",
            8: "Baby I'm a Star",
            9: "Purple Rain",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//2a783d64b0ea6d133eb7f6258ec1b6b0.jpg",
    ),
    Album(
        title="Born to Run",
        artist_id=17,
        track_data={
            1: "Thunder Road",
            2: "Tenth Avenue Freeze-Out",
            3: "Night",
            4: "Backstreets",
            5: "Born to Run",
            6: "She's the One",
            7: "Meeting Across the River",
            8: "Jungleland",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//2f9e7a75277e438197de13fdbf1cafdb.png",
    ),
    Album(
        title="Hotel California",
        artist_id=10,
        track_data={
            1: "Hotel California",
            2: "New Kid in Town",
            3: "Life in the Fast Lane",
            4: "Wasted Time",
            5: "Wasted Time (Reprise)",
            6: "Victim of Love",
            7: "Pretty Maids All in a Row",
            8: "Try and Love Again",
            9: "The Last Resort",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//c397bfa8a2b44bf2b5840ee716f99f07.png",
    ),
    Album(
        title="Back in Black",
        artist_id=16,
        track_data={
            1: "Hells Bells",
            2: "Shoot to Thrill",
            3: "What Do You Do for Money Honey",
            4: "Given the Dog a Bone",
            5: "Let Me Put My Love Into You",
            6: "Back in Black",
            7: "You Shook Me All Night Long",
            8: "Have a Drink on Me",
            9: "Shake a Leg",
            10: "Rock and Roll Ain't Noise Pollution",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//3b8bece5e8934f128b603a43409562b0.jpg",
    ),
    Album(
        title="The Wall",
        artist_id=3,
        track_data={
            1: "In the Flesh?",
            2: "The Thin Ice",
            3: "Another Brick in the Wall, Part 1",
            4: "The Happiest Days of Our Lives",
            5: "Another Brick in the Wall, Part 2",
            6: "Mother",
            7: "Goodbye Blue Sky",
            8: "Empty Spaces",
            9: "Young Lust",
            10: "One of My Turns",
            11: "Don't Leave Me Now",
            12: "Another Brick in the Wall, Part 3",
            13: "Goodbye Cruel World",
            14: "Hey You",
            15: "Is There Anybody Out There?",
            16: "Nobody Home",
            17: "Vera",
            18: "Bring the Boys Back Home",
            19: "Comfortably Numb",
            20: "The Show Must Go On",
            21: "In the Flesh",
            22: "Run Like Hell",
            23: "Waiting for the Worms",
            24: "Stop",
            25: "The Trial",
            26: "Outside the Wall",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//efc14f4cddf71190ca3a84d7779d98f6.jpg",
    ),
    Album(
        title="Highway to Hell",
        artist_id=16,
        track_data={
            1: "Highway to Hell",
            2: "Girls Got Rhythm",
            3: "Walk All Over You",
            4: "Touch Too Much",
            5: "Beating Around the Bush",
            6: "Shot Down in Flames",
            7: "Get It Hot",
            8: "If You Want Blood (You've Got It)",
            9: "Love Hungry Man",
            10: "Night Prowler",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//ef2f13102d7246fd8eaccc450d2c5728.jpg",
    ),
    Album(
        title="Born in the USA",
        artist_id=17,
        track_data={
            1: "Born in the USA",
            2: "Cover Me",
            3: "Darlington County",
            4: "Working on the Highway",
            5: "Downbound Train",
            6: "I'm on Fire",
            7: "No Surrender",
            8: "Bobby Jean",
            9: "I'm Goin' Down",
            10: "Glory Days",
            11: "Dancing in the Dark",
            12: "My Hometown",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//ff21d00803394d9c8a2e3d2300dd5335.png",
    ),
    Album(
        title="Pet Sounds",
        artist_id=18,
        track_data={
            1: "Wouldn't It Be Nice",
            2: "You Still Believe in Me",
            3: "That's Not Me",
            4: "Don't Talk (Put Your Head on My Shoulder)",
            5: "I'm Waiting for the Day",
            6: "Let's Go Away for Awhile",
            7: "Sloop John B",
            8: "God Only Knows",
            9: "I Know There's an Answer",
            10: "Here Today",
            11: "I Just Wasn't Made for These Times",
            12: "Pet Sounds",
            13: "Caroline, No",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//9146fecd89344956c9d3ab5d02c4fd22.png",
    ),
    Album(
        title="Exile on Main St.",
        artist_id=1,
        track_data={
            1: "Rocks Off",
            2: "Rip This Joint",
            3: "Shake Your Hips",
            4: "Casino Boogie",
            5: "Tumbling Dice",
            6: "Sweet Virginia",
            7: "Torn and Frayed",
            8: "Sweet Black Angel",
            9: "Loving Cup",
            10: "Happy",
            11: "Turd on the Run",
            12: "Ventilator Blues",
            13: "I Just Want to See His Face",
            14: "Let It Loose",
            15: "All Down the Line",
            16: "Stop Breaking Down",
            17: "Shine a Light",
            18: "Soul Survivor",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//fb57a2f660324cbacc8837ccdf5442a7.png",
    ),
    Album(
        title="OK Computer",
        artist_id=28,
        track_data={
            1: "Airbag",
            2: "Paranoid Android",
            3: "Subterranean Homesick Alien",
            4: "Exit Music (For a Film)",
            5: "Let Down",
            6: "Karma Police",
            7: "Fitter Happier",
            8: "Electioneering",
            9: "Climbing Up the Walls",
            10: "No Surprises",
            11: "Lucky",
            12: "The Tourist",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//62d26c6cb4ac4bdccb8f3a2a0fd55421.png",
    ),
    Album(
        title="Revolver",
        artist_id=2,
        track_data={
            1: "Taxman",
            2: "Eleanor Rigby",
            3: "I'm Only Sleeping",
            4: "Love You To",
            5: "Here, There and Everywhere",
            6: "Yellow Submarine",
            7: "She Said She Said",
            8: "Good Day Sunshine",
            9: "And Your Bird Can Sing",
            10: "For No One",
            11: "Doctor Robert",
            12: "I Want to Tell You",
            13: "Got to Get You into My Life",
            14: "Tomorrow Never Knows",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//deaec2d4735bea0d1c45fc75261624ae.jpg",
    ),
    Album(
        title="Ten",
        artist_id=30,
        track_data={
            1: "Once",
            2: "Even Flow",
            3: "Alive",
            4: "Why Go",
            5: "Black",
            6: "Jeremy",
            7: "Oceans",
            8: "Porch",
            9: "Garden",
            10: "Deep",
            11: "Release",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//4dfa0959e9534f8dcfd24d5dc5110589.jpg",
    ),
    Album(
        title="The Doors",
        artist_id=29,
        track_data={
            1: "Break On Through (To the Other Side)",
            2: "Soul Kitchen",
            3: "The Crystal Ship",
            4: "Twentieth Century Fox",
            5: "Alabama Song (Whisky Bar)",
            6: "Light My Fire",
            7: "Back Door Man",
            8: "I Looked at You",
            9: "End of the Night",
            10: "Take It as It Comes",
            11: "The End",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//24590e4ca3a94c748d6c8452ce52467b.png",
    ),
    Album(
        title="Appetite for Destruction",
        artist_id=20,
        track_data={
            1: "Welcome to the Jungle",
            2: "It's So Easy",
            3: "Nightrain",
            4: "Out Ta Get Me",
            5: "Mr. Brownstone",
            6: "Paradise City",
            7: "My Michelle",
            8: "Think About You",
            9: "Sweet Child o' Mine",
            10: "You're Crazy",
            11: "Anything Goes",
            12: "Rocket Queen",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//65f68c4738534c89a968bae93777d868.jpg",
    ),
    Album(
        title="What's Going On",
        artist_id=24,
        track_data={
            1: "What's Going On",
            2: "What's Happening Brother",
            3: "Flyin' High (In the Friendly Sky)",
            4: "Save the Children",
            5: "God Is Love",
            6: "Mercy Mercy Me (The Ecology)",
            7: "Right On",
            8: "Wholy Holy",
            9: "Inner City Blues (Make Me Wanna Holler)",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//8700ee8059d6cfaaf50e0bbf090d6e34.jpg",
    ),
    Album(
        title="Songs in the Key of Life",
        artist_id=24,
        track_data={
            1: "Love's in Need of Love Today",
            2: "Have a Talk with God",
            3: "Village Ghetto Land",
            4: "Contusion",
            5: "Sir Duke",
            6: "I Wish",
            7: "Knocks Me Off My Feet",
            8: "Pastime Paradise",
            9: "Summer Soft",
            10: "Ordinary Pain",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//02f18167ffe180e4a2f1c39594cfd94d.jpg",
    ),
    Album(
        title="Graceland",
        artist_id=31,
        track_data={
            1: "The Boy in the Bubble",
            2: "Graceland",
            3: "I Know What I Know",
            4: "Gumboots",
            5: "Diamonds on the Soles of Her Shoes",
            6: "You Can Call Me Al",
            7: "Under African Skies",
            8: "Homeless",
            9: "Crazy Love, Vol. II",
            10: "That Was Your Mother",
            11: "All Around the World or the Myth of Fingerprints",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//6dcd4921856a43fec390a969e8346838.png",
    ),
    Album(
        title="Bridge Over Troubled Water",
        artist_id=23,
        track_data={
            1: "Bridge Over Troubled Water",
            2: "El Condor Pasa (If I Could)",
            3: "Cecilia",
            4: "Keep the Customer Satisfied",
            5: "So Long, Frank Lloyd Wright",
            6: "The Boxer",
            7: "Baby Driver",
            8: "The Only Living Boy in New York",
            9: "Why Don't You Write Me",
            10: "Bye Bye Love",
            11: "Song for the Asking",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//6dc9fa47430462029c45ae207f9bfe20.jpg",
    ),
    Album(
        title="Automatic for the People",
        artist_id=27,
        track_data={
            1: "Drive",
            2: "Try Not to Breathe",
            3: "The Sidewinder Sleeps Tonite",
            4: "Everybody Hurts",
            5: "New Orleans Instrumental No. 1",
            6: "Sweetness Follows",
            7: "Monty Got a Raw Deal",
            8: "Ignoreland",
            9: "Star Me Kitten",
            10: "Man on the Moon",
            11: "Nightswimming",
            12: "Find the River",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//ceb7b050dee4411380a41135e7a68b16.png",
    ),
    Album(
        title="The Queen Is Dead",
        artist_id=15,
        track_data={
            1: "The Queen Is Dead",
            2: "Frankly, Mr. Shankly",
            3: "I Know It's Over",
            4: "Never Had No One Ever",
            5: "Cemetry Gates",
            6: "Bigmouth Strikes Again",
            7: "The Boy with the Thorn in His Side",
            8: "Vicar in a Tutu",
            9: "There Is a Light That Never Goes Out",
            10: "Some Girls Are Bigger Than Others",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//827fbd1bac1d3ed232ec6c95a2526139.png",
    ),
    Album(
        title="Blue Hawaii",
        artist_id=6,
        track_data={
            1: "Blue Hawaii",
            2: "Almost Always True",
            3: "Aloha Oe",
            4: "No More",
            5: "Can't Help Falling In Love",
            6: "Rock-A-Hula Baby",
            7: "Moonlight Swim",
            8: "Ku-u-i-po (Hawaiian Sweetheart)",
            9: "Ito Eats",
            10: "Slicin' Sand",
            11: "Hawaiian Sunset",
            12: "Beach Boy Blues",
            13: "Island of Love",
            14: "Hawaiian Wedding Song",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//708d6906a71a40d4bbd63cefb1509041.png",
    ),
    Album(
        title="Highway 61 Revisited",
        artist_id=7,
        track_data={
            1: "Like a Rolling Stone",
            2: "Tombstone Blues",
            3: "It Takes a Lot to Laugh, It Takes a Train to Cry",
            4: "From a Buick 6",
            5: "Ballad of a Thin Man",
            6: "Queen Jane Approximately",
            7: "Highway 61 Revisited",
            8: "Just Like Tom Thumb's Blue",
            9: "Desolation Row",
        },
        art="https://lastfm.freetls.fastly.net//i//u//300x300//c2312403b76a4d75b23b2b5134142d58.png",
    ),
    Album(
        title="Hybrid Theory",
        artist_id=32,
        track_data={
            "1": "Papercut",
            "2": "Now I See",
            "3": "Points of Authority",
            "4": "Plaster",
            "5": "Crawling",
            "6": "Runaway",
            "7": "The Untitled",
            "8": "By Myself",
            "9": "The Cure",
            "10": "The Cure For Mr. Hahn's Itch",
            "11": "A Place for My Head",
            "12": "Forgotten",
        },
        art="https://lastfm.freetls.fastly.net/i/u/300x300/c21b3923a4d3ff5629996f3f8e178140.jpg",
    ),
    Album(
        title="Horrorscope",
        artist_id=33,
        track_data={
            "1": "Rescue",
            "2": "Promise",
            "3": "On The Roof Again",
            "4": "Sunset Strip Bitch",
            "5": "Here's To The Night",
            "6": "Amphetamines",
            "7": "Enemy",
            "8": "Nocturnal",
            "9": "Jet Pack",
            "10": "Nightmare",
            "11": "Bang",
            "12": "Girl Eyes",
        },
        art="https://lastfm.freetls.fastly.net/i/u/300x300/5398c1afef3cb1165b4aa6875e3829e8.jpg",
    ),
    Album(
        title="Half Hour Of Power",
        artist_id=34,
        track_data={
            "1": "Grab the Devil by the Horns and Fuck Him Up the Ass",
            "2": "Machine Gun",
            "3": "What I Believe",
            "4": "T.H.T.",
            "5": "Makes No Difference",
            "6": "Summer",
            "7": "32 Ways to Die",
            "8": "Second Chance for Max Headroom",
            "9": "Dave's Possessed Hair/It's What We're All About",
            "10": "Ride the Chariot to the Devil",
            "11": "Another Time Around",
        },
        art="https://lastfm.freetls.fastly.net/i/u/300x300/8f73ce89d7d24aa6b6a1064cf04c2deb.png",
    ),
    Album(
        title="This Time Next Year",
        artist_id=35,
        track_data={
            "1": "I Hope You Die Soon",
            "2": "10 Seconds Too Late",
            "3": "This Time Next Year",
            "4": "Once in a Row",
            "5": "Self-Destruct",
            "6": "Deal With It",
            "7": "Single White Female",
            "8": "Pinky Swear",
            "9": "How Can You Even Face Me?",
            "10": "Me and You vs. Them",
            "11": "Another Friend",
            "12": "It's Monday and Raining",
        },
        art="https://lastfm.freetls.fastly.net/i/u/300x300/a38a9e24b5f94f3ccff6b24ebeeddca1.jpg",
    ),
    Album(
        title="Warning",
        artist_id=36,
        track_data={
            "1": "Warning",
            "2": "Blood, Sex and Booze",
            "3": "Church on Sunday",
            "4": "Fashion Victim",
            "5": "Castaway",
            "6": "Misery",
            "7": "Deadbeat Holiday",
            "8": "Hold On",
            "9": "Jackass",
            "10": "Waiting",
            "11": "Minority",
            "12": "Macy's Day Parade",
        },
        art="https://lastfm.freetls.fastly.net/i/u/300x300/81572808c194de841fef009c56f91deb.jpg",
    ),
]
