"""join table for watchlist

Revision ID: 21f936dd165e
Revises: 1cdcb3096842
Create Date: 2024-11-23 15:24:39.891381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f936dd165e'
down_revision: Union[str, None] = '1cdcb3096842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_items_release_id'), 'items', ['release_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_release_id'), table_name='items')
    # ### end Alembic commands ###
