"""watchlist

Revision ID: 589d4d8b6813
Revises: 1cdcb3096842
Create Date: 2024-11-23 16:58:17.627615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589d4d8b6813'
down_revision: Union[str, None] = '1cdcb3096842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'release_id')
    )
    op.create_index(op.f('ix_items_release_id'), 'items', ['release_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_release_id'), table_name='items')
    op.drop_table('watchlist')
    # ### end Alembic commands ###
