"""pray

Revision ID: 989ef892b244
Revises:
Create Date: 2024-12-03 18:07:47.618866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "989ef892b244"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "albums",
        "art",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=True,
        schema="wax_exchange",
    )
    op.create_index(
        op.f("ix_wax_exchange_albums_title"),
        "albums",
        ["title"],
        unique=False,
        schema="wax_exchange",
    )
    op.create_index(
        op.f("ix_wax_exchange_artists_name"),
        "artists",
        ["name"],
        unique=False,
        schema="wax_exchange",
    )
    op.add_column(
        "items",
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="wax_exchange",
    )
    op.add_column(
        "items",
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        schema="wax_exchange",
    )
    op.create_index(
        op.f("ix_wax_exchange_releases_media_type"),
        "releases",
        ["media_type"],
        unique=False,
        schema="wax_exchange",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wax_exchange_releases_media_type"),
        table_name="releases",
        schema="wax_exchange",
    )
    op.drop_column("items", "updated", schema="wax_exchange")
    op.drop_column("items", "created", schema="wax_exchange")
    op.drop_index(
        op.f("ix_wax_exchange_artists_name"),
        table_name="artists",
        schema="wax_exchange",
    )
    op.drop_index(
        op.f("ix_wax_exchange_albums_title"), table_name="albums", schema="wax_exchange"
    )
    op.alter_column(
        "albums",
        "art",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
        schema="wax_exchange",
    )
    op.create_table(
        "alembic_version",
        sa.Column(
            "version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("version_num", name="alembic_version_pkc"),
        schema="wax_exchange",
    )
    # ### end Alembic commands ###
