"""indexes

Revision ID: efaa804318c3
Revises: 34cfdd8d1a98
Create Date: 2024-11-30 23:10:14.153380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efaa804318c3'
down_revision: Union[str, None] = '34cfdd8d1a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_albums_title'), 'albums', ['title'], unique=False)
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_index(op.f('ix_releases_media_type'), 'releases', ['media_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_releases_media_type'), table_name='releases')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_index(op.f('ix_albums_title'), table_name='albums')
    # ### end Alembic commands ###
