"""Production Schema

Revision ID: fe1ef55063d7
Revises: 
Create Date: 2024-11-30 02:10:39.369037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1ef55063d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='wax_exchange'
    )
    op.create_index(op.f('ix_wax_exchange_artists_id'), 'artists', ['id'], unique=False, schema='wax_exchange')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='wax_exchange'
    )
    op.create_index(op.f('ix_wax_exchange_users_email'), 'users', ['email'], unique=True, schema='wax_exchange')
    op.create_index(op.f('ix_wax_exchange_users_id'), 'users', ['id'], unique=False, schema='wax_exchange')
    op.create_index(op.f('ix_wax_exchange_users_username'), 'users', ['username'], unique=True, schema='wax_exchange')
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('art', sa.String(length=100), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('track_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['wax_exchange.artists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='wax_exchange'
    )
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('variant', sa.String(length=100), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['wax_exchange.albums.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='wax_exchange'
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['wax_exchange.users.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['wax_exchange.releases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='wax_exchange'
    )
    op.create_index(op.f('ix_wax_exchange_items_owner_id'), 'items', ['owner_id'], unique=False, schema='wax_exchange')
    op.create_index(op.f('ix_wax_exchange_items_release_id'), 'items', ['release_id'], unique=False, schema='wax_exchange')
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['wax_exchange.users.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['wax_exchange.releases.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['wax_exchange.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='wax_exchange'
    )
    op.create_index(op.f('ix_wax_exchange_orders_buyer_id'), 'orders', ['buyer_id'], unique=False, schema='wax_exchange')
    op.create_index(op.f('ix_wax_exchange_orders_id'), 'orders', ['id'], unique=False, schema='wax_exchange')
    op.create_index(op.f('ix_wax_exchange_orders_release_id'), 'orders', ['release_id'], unique=False, schema='wax_exchange')
    op.create_index(op.f('ix_wax_exchange_orders_seller_id'), 'orders', ['seller_id'], unique=False, schema='wax_exchange')
    op.create_table('watchlist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['wax_exchange.releases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wax_exchange.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'release_id'),
    schema='wax_exchange'
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['wax_exchange.items.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['wax_exchange.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='wax_exchange'
    )
    op.create_index(op.f('ix_wax_exchange_listings_item_id'), 'listings', ['item_id'], unique=False, schema='wax_exchange')
    op.create_index(op.f('ix_wax_exchange_listings_seller_id'), 'listings', ['seller_id'], unique=False, schema='wax_exchange')
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['wax_exchange.orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wax_exchange.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='wax_exchange'
    )
    op.create_index(op.f('ix_wax_exchange_reviews_user_id'), 'reviews', ['user_id'], unique=False, schema='wax_exchange')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wax_exchange_reviews_user_id'), table_name='reviews', schema='wax_exchange')
    op.drop_table('reviews', schema='wax_exchange')
    op.drop_index(op.f('ix_wax_exchange_listings_seller_id'), table_name='listings', schema='wax_exchange')
    op.drop_index(op.f('ix_wax_exchange_listings_item_id'), table_name='listings', schema='wax_exchange')
    op.drop_table('listings', schema='wax_exchange')
    op.drop_table('watchlist', schema='wax_exchange')
    op.drop_index(op.f('ix_wax_exchange_orders_seller_id'), table_name='orders', schema='wax_exchange')
    op.drop_index(op.f('ix_wax_exchange_orders_release_id'), table_name='orders', schema='wax_exchange')
    op.drop_index(op.f('ix_wax_exchange_orders_id'), table_name='orders', schema='wax_exchange')
    op.drop_index(op.f('ix_wax_exchange_orders_buyer_id'), table_name='orders', schema='wax_exchange')
    op.drop_table('orders', schema='wax_exchange')
    op.drop_index(op.f('ix_wax_exchange_items_release_id'), table_name='items', schema='wax_exchange')
    op.drop_index(op.f('ix_wax_exchange_items_owner_id'), table_name='items', schema='wax_exchange')
    op.drop_table('items', schema='wax_exchange')
    op.drop_table('releases', schema='wax_exchange')
    op.drop_table('albums', schema='wax_exchange')
    op.drop_index(op.f('ix_wax_exchange_users_username'), table_name='users', schema='wax_exchange')
    op.drop_index(op.f('ix_wax_exchange_users_id'), table_name='users', schema='wax_exchange')
    op.drop_index(op.f('ix_wax_exchange_users_email'), table_name='users', schema='wax_exchange')
    op.drop_table('users', schema='wax_exchange')
    op.drop_index(op.f('ix_wax_exchange_artists_id'), table_name='artists', schema='wax_exchange')
    op.drop_table('artists', schema='wax_exchange')
    # ### end Alembic commands ###
